# Generated by Django 5.2.16 on 2026-07-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_content_alter_pagesection_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='layout_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured page content used by the website layout.'),
        ),
    ]
