# Generated by Django 5.1.4 on 2026-07-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_layout_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='layout_data',
        ),
    ]
