# Generated by Django 5.1.4 on 2026-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('department', models.CharField(choices=[('academic', 'Academic Staff'), ('administrative', 'Administrative Staff'), ('support', 'Support Staff'), ('management', 'Management'), ('other', 'Other')], default='academic', max_length=30)),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full-time', max_length=20)),
                ('location', models.CharField(blank=True, default='Bunga Hill Campus, Kampala', max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True)),
                ('application_email', models.EmailField(blank=True, max_length=254)),
                ('pdf_details', models.FileField(blank=True, null=True, upload_to='careers/')),
                ('is_active', models.BooleanField(default=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-posted_date'],
            },
        ),
    ]
