# Generated by Django 5.1.4 on 2026-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admission Process Step',
                'verbose_name_plural': 'Admission Process Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('postgraduate', 'Postgraduate')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admission Requirement',
                'verbose_name_plural': 'Admission Requirements',
                'ordering': ['order', 'level'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2025/2026', max_length=20)),
                ('programme', models.CharField(max_length=300)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('student_type', models.CharField(choices=[('local', 'Local Student'), ('international', 'International Student'), ('government', 'Government Sponsored')], default='local', max_length=20)),
                ('intake', models.CharField(blank=True, choices=[('april', 'April Intake'), ('august', 'August Intake')], max_length=20)),
                ('tuition_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tuition_per_semester', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('functional_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['order', 'programme'],
            },
        ),
    ]
