# Generated by Django 5.1.4 on 2026-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Community', 'Community'), ('Student Life', 'Student Life'), ('Partnerships', 'Partnerships'), ('Research', 'Research'), ('Events', 'Events'), ('Finance', 'Finance'), ('Announcements', 'Announcements'), ('Academics', 'Academics'), ('Awards', 'Awards')], max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('text', models.TextField(help_text='Short summary / excerpt')),
                ('body', models.TextField(blank=True, help_text='Full article content (HTML or Markdown)')),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('image_url', models.CharField(blank=True, help_text='External image URL if not uploading', max_length=500)),
                ('href', models.CharField(blank=True, help_text='External link if article is hosted elsewhere', max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('issue_number', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='newsletter/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='newsletter/pdfs/')),
                ('pdf_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('published_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-published_date'],
            },
        ),
    ]
