# Generated by Django 5.1.4 on 2026-07-07 07:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Full article content'),
        ),
    ]
