# Generated by Django 5.1.4 on 2026-07-06 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('programme', models.CharField(blank=True, max_length=300)),
                ('current_position', models.CharField(blank=True, max_length=300)),
                ('current_organisation', models.CharField(blank=True, max_length=300)),
                ('bio', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='alumni/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alumni Profile',
                'verbose_name_plural': 'Alumni Profiles',
                'ordering': ['order', '-graduation_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlumniTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (can differ from profile)', max_length=200)),
                ('programme', models.CharField(blank=True, max_length=200)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('testimonial', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='alumni/testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('alumni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='alumni.alumniprofile')),
            ],
            options={
                'verbose_name': 'Alumni Testimonial',
                'verbose_name_plural': 'Alumni Testimonials',
                'ordering': ['order'],
            },
        ),
    ]
