# Generated by Django 5.1.4 on 2026-07-06 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='collaborations/')),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Collaboration / Partner',
                'verbose_name_plural': 'Collaborations & Partners',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, max_length=200)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField(blank=True)),
                ('cta', models.CharField(default='Learn More', max_length=100)),
                ('cta_href', models.CharField(blank=True, default='/admissions', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('image_url', models.CharField(blank=True, help_text='Relative or external URL if not uploading', max_length=500)),
                ('image_position', models.CharField(blank=True, default='center center', max_length=100)),
                ('programme_1', models.CharField(blank=True, max_length=200)),
                ('programme_2', models.CharField(blank=True, max_length=200)),
                ('programme_3', models.CharField(blank=True, max_length=200)),
                ('programme_4', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nav Child',
                'verbose_name_plural': 'Nav Children',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('href', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('disable_link', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('href', models.CharField(max_length=300)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quick Link',
                'verbose_name_plural': 'Quick Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(default='King Ceasor University', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('short_name', models.CharField(default='KCU', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True, default='https://kcu.ac.ug')),
                ('apply_url', models.URLField(blank=True, default='https://apply.kcu.ac.ug/')),
                ('academia_url', models.URLField(blank=True, default='https://academia.kcu.ac.ug/')),
                ('kclass_url', models.URLField(blank=True, default='https://vclass.kcu.ac.ug/')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, help_text='e.g. Dr, Prof, Mr', max_length=100)),
                ('position', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('management', 'University Management'), ('academic', 'Academic Staff'), ('support', 'Support Staff'), ('guild', 'Guild Leadership')], default='management', max_length=30)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NavGrandChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navchild')),
            ],
            options={
                'verbose_name': 'Nav Grand Child',
                'verbose_name_plural': 'Nav Grand Children',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='navchild',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navitem'),
        ),
    ]
