# Generated by Django 5.1.4 on 2026-07-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitecontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteContent',
        ),
    ]
